// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzmkb0EJX2OGhX-S6WoyTxitZBEOcrrEU',
    appId: '1:557867696521:web:f66cca961b5b9319886158',
    messagingSenderId: '557867696521',
    projectId: 'proposalmanagmentsystem',
    authDomain: 'proposalmanagmentsystem.firebaseapp.com',
    storageBucket: 'proposalmanagmentsystem.appspot.com',
    measurementId: 'G-CCBXGF3MFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHzQFTTINC9kqc4ljVBojh1X1VqzezSLc',
    appId: '1:557867696521:android:b4a056e96118facd886158',
    messagingSenderId: '557867696521',
    projectId: 'proposalmanagmentsystem',
    storageBucket: 'proposalmanagmentsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnA0ct_VkTQe6b-W38MdCyfeMUXDxFBEw',
    appId: '1:557867696521:ios:065e1a34d4f2803a886158',
    messagingSenderId: '557867696521',
    projectId: 'proposalmanagmentsystem',
    storageBucket: 'proposalmanagmentsystem.appspot.com',
    iosBundleId: 'com.example.managmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnA0ct_VkTQe6b-W38MdCyfeMUXDxFBEw',
    appId: '1:557867696521:ios:065e1a34d4f2803a886158',
    messagingSenderId: '557867696521',
    projectId: 'proposalmanagmentsystem',
    storageBucket: 'proposalmanagmentsystem.appspot.com',
    iosBundleId: 'com.example.managmentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzmkb0EJX2OGhX-S6WoyTxitZBEOcrrEU',
    appId: '1:557867696521:web:24e22997d57cdee9886158',
    messagingSenderId: '557867696521',
    projectId: 'proposalmanagmentsystem',
    authDomain: 'proposalmanagmentsystem.firebaseapp.com',
    storageBucket: 'proposalmanagmentsystem.appspot.com',
    measurementId: 'G-FPW40XPWBG',
  );
}
